# Generated by Django 5.2.5 on 2025-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnews',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='video',
            field=models.FileField(upload_to='news_videos/'),
        ),
    ]
